### ISSUE TITLE
Digital input gate

### ISSUE THREAD

**Issue by peifferjd** [peifferjd/ClosedLoopGamma#6]
It just occurred to me that we should include a digital input that gates the closed-loop output. This is useful in experiments where you only want the stimulation to occur during particular task/behavioral epochs that are detected using other hardware.

**Comment by jdpeiffer6** [comment]
Should suppress output when input gate is high:

```
if(digitalRead(INPUT_GATE_PIN)==LOW){
            digitalWrite(TRIGGERING_PIN, HIGH);
          }
```
